version: "3.3"

services:
  web:
    image: 127.0.0.1:5000/stackdemo
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
  redis:
    image: redis:alpine
    deploy:
      mode: global