version: '3.7'

services:
  image-prune:
    image: docker
    command: sh -c "while true; do docker image prune -af; sleep 120; done"
    networks:
      - bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global

networks:
  bridge:
    external: true
    name: bridge