version: '3.7'

services:
  image-prune:
    image: docker
    command: sh -c "docker run --rm --privileged --name test busybox sleep infinity"
    networks:
      - bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global

networks:
  bridge:
    external: true
    name: bridge