version: '3.7'

services:
  image-prune:
    image: docker
    command: sh -c "while true; do docker pull alpine:latest; docker pull hello-world; docker pull busybox:latest; sleep 86400; done"
    networks:
      - bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global

networks:
  bridge:
    external: true
    name: bridge